### ISSUE TITLE
how to sniff the traffic of fast-DDS if the transport layer is using Shared Memory?

### ISSUE THREAD

**Issue by carlstand** [eProsima/Non-Intrusive-DDS-Recorder#4]
if it only analyze the pcap file, then i assume it's not possible to sniff the traffic transported by SHM? 
is there any workaround to sniff that part of traffic? thanks!

**Comment by JLBuenoLopez** [comment]
I will close this issue as it has been answered in eProsima/Fast-DDS#1890.
